services:
  pingvin-share-x:
    container_name: pingvin-share-x
    image: smp46/pingvin-share-x
    restart: unless-stopped
    environment:
      TRUST_PROXY: "true"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${DATA_DIR}/pingvin-share/data:/opt/app/backend/data"
      - "${DATA_DIR}/pingvin-share/images:/opt/app/frontend/public/img"
    networks:
      - proxy

networks:
  proxy:
    external: true
