services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DATA_DIR}/dockge:/app/data"
      - "${DOCKER_DIR}:${DOCKER_DIR}"
    environment:
      DOCKGE_STACKS_DIR: "${DOCKER_DIR}"
    networks:
      - proxy

networks:
  proxy:
    external: true
